name: SSH into VM to pull new updates
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Pull the new files from Github
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: cd KCServersBot && git reset --hard HEAD && git pull
